apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: nodejs-openshift-ex
  name: nodejs-openshift-ex
spec:
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-openshift-ex:latest
  source:
    git:
      ref: master
      uri: https://github.com/shaundomingo/nodejs-openshift-ex.git
    type: Git
  strategy:
    type: Docker
